### ISSUE TITLE
swift package manager dependency resolution fails

### ISSUE THREAD

**Issue by bolu-atx** [DimaRU/Libssh2Prebuild#3]
```
Computing version for https://github.com/DimaRU/Libssh2Prebuild.git
error: Dependencies could not be resolved because no versions of 'libssh2prebuild' match the requirement 1.9.0..<2.0.0 and root depends on 'libssh2prebuild' 1.9.0..<2.0.0.
```

How it's specified
```
        .package(name: "CSSH", url: "https://github.com/DimaRU/Libssh2Prebuild.git", from: "1.9.0")
```

Swift version:
```
~/Github/Shout (master) » swift --version                                                                                                                                                                     bolu@USSD-OLM-1337MBAM1
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by bolu-atx** [comment]
Thank you for providing this pre-built library, it's really helpful! I noticed this issue while trying to use your forked version of Shout. Let me know if this is expected? Not sure if the git tagged + string has something to do with it.

**Comment by bolu-atx** [comment]
just FYI, I forked your repo here and tagged it with a semantic version tag `v1.10.0` and confirmed that SPM is able to successfully resolve this version tag.

**Comment by DimaRU** [comment]
This is because .binaryTarget is swift 5.3 feature, but original Shout repo used "swift-tools-version:5.0".
