### ISSUE TITLE
Unable to use with shout

### ISSUE THREAD

**Issue by JBergsee** [DimaRU/Libssh2Prebuild#5]
Using `.package(name: "CSSH", url: "https://github.com/DimaRU/Libssh2Prebuild.git", from: "1.9.0")`gives the following error message:
`Failed to resolve dependencies Dependencies could not be resolved because no versions of 'libssh2prebuild' match the requirement 1.0.0..<2.0.0 and root depends on 'libssh2prebuild' 1.9.0..<2.0.0.`

**Comment by DimaRU** [comment]
Fixed right now.
